### ISSUE TITLE
Backup of Collection with other collection but with empty document fields

### ISSUE THREAD

**Issue by Jaimeer** [willhlaw/node-firestore-backup-restore#22]
I have detected that if you have a collection that contains an empty document with no fields but with another collection, the data is not saved.

Collection_1
* Document_1
  * Fields
    * Field_1
    * Field_2
  * Collections
    * Collection_1_1
      * ...
* Document_2
  * Fields
  * Collections
    * Collection_2_1
      * ...

The Collection_2_1 is not saved because the Document_1 doesn't have fields, if you add a field to the Document_2, the data is saved in the backup process

**Comment by NaturalLam** [comment]
That's a FireStore issue, basically if you have this structure and you have the collection reference of Collection_1 (say `ref`), and call ref.get(), it does not return Document_2 as it's being regarded as empty.
see this issue: https://stackoverflow.com/questions/48498342/firestore-query-documents-with-only-collections-inside?rq=1

**Comment by willhlaw** [comment]
I agree. Collections_2_1 are "orphaned" and a Firestore issue. Closing for now, but would be interested to see if anyone has thoughts for how to access the orphaned docs.
