### ISSUE TITLE
Authentication users backup

### ISSUE THREAD

**Issue by blaforet** [willhlaw/node-firestore-backup-restore#26]
Hi 
First, thank you for this backup/restore solutions.
Did a clone and worked fine.
I have a dought,  the collection Users is backup but not the actual "Authentication users".
So if clone the DB and want to use it, when registering /signin, firebase will give a new User ID. Therefore, the user will not have is previous config and other data access. 

Any solutions?
Thank you

**Comment by willhlaw** [comment]
Absolutely.  Here is what has worked for me.

```
> firebase use backup-firebase-project-id
> firebase auth:export userExport.json
> firebase use restore-firebase-project-id
> firebase auth:import --hash-algo='SCRYPT' --salt-separator='<from-hash-params==>' --rounds=8 --mem-cost=14 --hash-key='<from-hash-params==>' --project='restore-firebase-project-id' userExport.json
```

To figure out what should go in the `<from-hash-params==>` in the above command line, find your hash parameters through firebase admin now. Navigate to

> Console > Project > Authentication > Three little dots on right side of all users > Password Hash Credentials

![](https://user-images.githubusercontent.com/2853953/35457716-db81e07e-02a7-11e8-872a-709d4ef9f3b1.png)

To see more about export and import the auth users, see the official command line documentation: https://firebase.google.com/docs/cli/auth-import.

To help you troubleshoot the command and what to use for your hash parameters, see https://github.com/firebase/firebase-tools/issues/253.

Please let me know if that works for you.

**Comment by blaforet** [comment]
Hi Will
Yes, it did work perfectly, thank you.
