### ISSUE TITLE
Restore option not working

### ISSUE THREAD

**Issue by mgs96** [willhlaw/node-firestore-backup-restore#47]
Hello, I had previously made a backup and now I want to restore but unfortunatelly I keep getting this error:
var childFieldObject = value.reduce(function (acc, cur) {
                                   ^

TypeError: Cannot read property 'reduce' of undefined
    at /home/developer/.nvm/versions/node/v8.11.3/lib/node_modules/firestore-backup-restore/build/lib/FirestoreDocument.js:79:36

thanks in advance

**Comment by johnstonmatt** [comment]
+1 my backup was made from ' steadyequipment/node-firestore-backup' with pretty print this tool says restore complete, but the data is not reflected in the console

**Comment by rupertbulquerin** [comment]
same issue.. any fix for this yet?
